### ISSUE TITLE
surface.poll_events() is always one or zero events per frame

### ISSUE THREAD

**Issue by Avokadoen** [phaazon/luminance-rs#255]
I might be doing something wrong, but creating a for loop like this:
```rust
for event in surface.poll_events() {
      println!("{:?}", event);
}
```
and it seems like pressing multiple buttons i.e A and W will only fire event for one of those

**Comment by phaazon** [comment]
Depending on how GLFW / glutin are going to queue those events, you should get them one after another.

**Comment by Avokadoen** [comment]
I am sorry i was probably unclear. For each frame there seems to only be 1 or 0 events no matter how many inputs you activate for given frame.

**Comment by phaazon** [comment]
Wait. You want to have several inputs for each frame? The thing is, we use a `for` loop here because the speed at which you render is not bound to the speed at which the user interacts with the program. What it means is that if you call `poll_events` not frequently, the events queue will grow. The `for` allow to treat all those events. That might happen when the `poll_events` is on the same thread as the render, which is almost all the time the case. Then, if your render is too slow, you will not call `poll_events` frequently enough and will get queued events. However, this is also true if you enable key repeat — you should get several events in the queue.

When you say “activate inputs for a given frame”, what do you mean exactly?

**Comment by Avokadoen** [comment]
Is there an event for key down and key up then? I would like to know when the user holds down multiple keys. Thanks for your response :+1:

**Comment by Avokadoen** [comment]
Is this the [key callback](https://www.glfw.org/docs/latest/group__input.html#ga7e496507126f35ea72f01b2e6ef6d155) function exposed or would i have to extende luminance-glfw to make it work?

**Comment by phaazon** [comment]
Currently, you can do it by pattern-matching on `Action` (glfw) for instance, and storing the state of keys to determine which one is pressed. I also plan to give people more freedom about how the windowing crates work — i.e. by removing the re-exports and the `Surface` trait, basically.

**Comment by phaazon** [comment]
I’m closing this because lots of things have happened to the windowing / system crates.
