### ISSUE TITLE
Allow access to window handle in luminance-windowing

### ISSUE THREAD

**Issue by suleyth** [phaazon/luminance-rs#294]
Right now the only way to render with `luminance` is using the `GlfwSurface` or `GlutinSurface` structures, which provide events, cursor hiding, fullscreen support and setting samples. That's... about it.

Any serious game/engine will probably want to code more things with the platform layer, but with this system you're forced to use the `Surface` trait for everything. I understand that `luminance` requires a very specific setup, and this system is a good way of abstracting it out, so it probably isn't a good idea to change it to something else.

I think this could be easily solved, and without the need to change anything, by just making a way to get the window handle. So, for example, `luminance-glfw` would have a `get_handle(surface: &GlfwSurface) -> glfw::Window` function.

That way if you ever need to use `glfw::Window` for anything you can just get it instead of having to implement the trait yourself. If you like this idea, I can make a pull request.

**Comment by phaazon** [comment]
Hey!

So, you’re right, the current situation is meh. But I’ve been using `luminance-glutin` to experiment a new API lately. I plan to deprecate `luminance-windowing`’s `Surface` trait.

Have a look at [this](https://docs.rs/luminance-glutin/0.8.2/luminance_glutin/struct.GlutinSurface.html#method.from_builders) for instance. I plan to do the same thing for all windowing crates. The goal is to make `luminance-*` just _builders_ into the native underyling windowing crate, instead of sinking them into a weird and uncomfortable abstraction.

The _abstracting out_ thing you’re talking about is not really linked to `luminance`. `luminance` is _just_ liked to “how to render a frame.” The rest should be as close as what the native windowing crate does. `luminance-windowing` prevents that. The first time I realized it would be a problem is when I saw how `glutin` handles events (i.e. it works with a closure). It prevents to implement the `Surface::poll_events` method correctly (and even `Surface::wait_events` cannot be implemented; it was a `panic!` lately).

So my idea to this, already present in `luminance-glutin`, is to build the graphics context via a type, like `GlutinSurface`, allowing people to customize _as they would normally do_.

The only drawback that I need to explore is whether they can fuck up something later on with contexts, since `luminance` heavily depends (currently) on how context and threads are used.

**Comment by suleyth** [comment]
I'm pretty sure both GLFW and Glutin have a way of retrieving the OpenGL context parameters. Maybe you can just check those and return `Err(<Something>)`. Or even just panicking with a good enough error message could work.

That way even if they recreate the context with different parameters, or in a different thread, (which *does* seem something very unusual that nobody should probably do) you can be sure it will fail.

**Comment by phaazon** [comment]
> Edit: Though even with that new window system, I still think you should be able to get the window handle. There's still a lot missing: Querying monitors, setting if the window is resizable, setting the icon, set the title and size at runtime, set the opacity, start the window hidden, etc...

Have you clicked the link I posted? The `WindowBuilder`-based closure allows you to do all this, with [this](https://docs.rs/glutin/0.21.2/glutin/struct.WindowBuilder.html#method.with_resizable), for instance.

**Comment by phaazon** [comment]
[GlutinSurface](https://docs.rs/luminance-glutin/0.8.2/luminance_glutin/struct.GlutinSurface.html) gives you access to its underlying `glutin` objects, so you have access to both the context and the events loop.

**Comment by othelarian** [comment]
Hi, to add something to the discussion, I recently start to use luminance, but with a need to multi windowing. Actually it's really easy to build something completely different with the luminance-glutin as example, as the code is pretty simple to read and hack on. The only issue is with the GraphicsState, but it's a different subject.
For a game engine/video game, or something which require a deeper integration with window handle, it's more like you need to rewrite luminance-glutin/gflw, but it isn't a big deal, and the lib already bring all the basics. Trying to tight up luminance to glutin sounds more applicable to specific lib than a basic integration, imho.
As a PoC, you can check this repo: https://github.com/othelarian/nikut . It's currently not fully functional, but it use glutin v0.22 and you still can use it for a single window (commit 5378c88ca9cce7deb462ead5587556e5ca6dd0b3  work with a single window).

**Comment by zicklag** [comment]
Somewhat related to this topic, I started to use Luminance for the Bevy game engine, which handles windowing, input events, etc. all by itself and instead provides `winit` Window or a [`raw-window-handle`](https://docs.rs/raw-window-handle/0.3.3/raw_window_handle/) that I have to create a GL context for. This separates the context creation completely from the window creation which is convenient from an API perspective because then the luminance bindings don't have anything to do with the Window, but inconvenient because `glutin` doesn't like it when it isn't the one that creates the window.

Because of that, instead of using `glutin` I used [`surfman`](https://docs.rs/surfman) to create the context from the Winit window in the [`luminance-surfman`](https://github.com/katharostech/luminance-surfman) crate, and you can use that to create a Luminance surface from _any_ winit window. While it's not implemented yet, it would literally take 15 minutes to add support to `luminance-surfman` to be able to create Luminance surfaces from any raw window handle. That would work for `glfw` windows or anything else I think.

---

Anyway, the point is, maybe using something like `luminance-surfman` would allow us to abstract away the creation and customization of the window and put that burden on the game/app developer. They use whatever they want to create/customize the window. Then they pass the raw window handle to Luminance to create the surface.

The biggest caveat to the `surfman` approach is that, because we don't have control over the window creation or the event loop, you have to manually call [`set_size`](https://github.com/katharostech/luminance-surfman/blob/9b71ccb465121a2be09fbcbb8777c84e7ad07b58/src/lib.rs#L158) on the luminance surface whenever the window resizes.

**Comment by phaazon** [comment]
Is there anything else blocking this issue? The `Window` object is accessible in `luminance-glutin` (same in `luminance-glfw`). I’m deprecating more and more features from `luminance-windowing` as it doesn’t scale and that it’s platform-specific code, meaning that people should pick a platform crate (or use another layer of abstraction for that).

I’m closing the issue but feel free to comment if you think something is still missing.

**Comment by zicklag** [comment]
I've been able to do everything I've needed to in Luminance so far, even if it was by writing my own platform crate it was super simple and to be expected anyway given the diversity of target's you'd want to be able to port to. Seems like this is reasonable to offload onto people who want to make integrations with Luminance as it is target specific anyway. :+1:
