### ISSUE TITLE
Incorrect data uploaded using VertexSemantics

### ISSUE THREAD

**Issue by Lucky4Luuk** [phaazon/luminance-rs#309]
**Confusing explanation of the problem I encountered:**
Basically, the shader accepted a vertex position, normal, color and uv coord.
I used the vertexsemantics to upload this data. But, when checking if the uv coords were correctly being loaded and uploaded to the shader, I changed my shader to output the uv coords directly, instead of doing all my lighting stuff.

The problem now is that I stopped using the normal data and the color data.
The moment I stopped using those, the uv data in the shader was suddenly incorrect.
When I just uploaded the normal data and the color data (which was [1.0; 1.0; 1.0] in this case) and used it, the uv coords were suddenly correct again (I checked this by multiplying the final color with the uv coords, as the color was 1,1,1 and the lighting impact was minimal in this test case).

Not really a huge issue but can definitely lead to some headscratching problems :p

**Comment by phaazon** [comment]
Do you think you can write a reproducible example? It would be super cool, because I still struggle to understand what you mean. How did you check the UV coords? How did you used the normal and color data in the first place?

Also, if we confirm the bug, may you add your OS and your OpenGL driver (and the windowing backend you’re using), pretty please? :)

**Comment by phaazon** [comment]
(Can you show the shader you’re using, too?)
