### ISSUE TITLE
[luminance-glutin] Re-export of glutin removed

### ISSUE THREAD

**Issue by iwikal** [phaazon/luminance-rs#410]
It was very handy to not have to think about what version of glutin to install, and just allow luminance-glutin to control that, but the re-export disappeared in v0.10 in this commit: 3d0703810739801f08374cd86fea42a238f44dda

**Comment by phaazon** [comment]
Yes, sorry, it’s on purpose. Re-exporting `glutin` makes `luminance-glutin` a _forward-like_ crate, and either I need to know everything useful that must be re-exported, or simply re-export everything. People will still have to go through `glutin` documentation to do whatever they want to (mouse, keyboard, system events, etc.), since it’s not the job of `luminance`.
