### ISSUE TITLE
Can I specify shader version?

### ISSUE THREAD

**Issue by qingxiang-jia** [phaazon/luminance-rs#511]
When I specify shader version, during run time, I get error:

> thread 'main' panicked at 'program creation: StageError(CompilationFailed(VertexShader, "0:3(1): preprocessor error: #version must appear on the first line\n\u{0}"))', src/main.rs:90:6

I did notice that all example shaders don't have a version specified so I suspected this might be intentional, but I didn't find any documentation for this behavior. It would be great if I can specify it because then I can run glslangValidator in my text editor to get some validation (otherwise it will just complaint I didn't have any version specify and default to the lowest version).

Background: I am learning shader and rust, but the book uses some C++ library that I don't want to touch. I found luminance and it is a life saver.

**Comment by robert-chiniquy** [comment]
This error is due to Luminance adding the version to each shader when the program is loaded: https://github.com/phaazon/luminance-rs/blob/0c3790e25e5757f73d7bdd30c7dad185a7576ef4/luminance-webgl/src/webgl2/shader.rs#L303

The error message is because the browser is seeing a shader with 2 version declarations, the second one is violating that rule. 

A good tool for troubleshooting stuff like this in the browser is Spector.js: https://spector.babylonjs.com/ It will let you capture webgl state and view the shaders which are currently loaded (so you can see where errors like this are coming from).

**Comment by qingxiang-jia** [comment]
Hi @robert-chiniquy , thanks for the help. So the linked code hard code version 300 to each shader. That solves my issue: I can't specify the version number manually. Personally, I think it would be nice for luminance not to do this as if my GPU supports higher version, I would like to use newer features.

**Comment by robert-chiniquy** [comment]
Oh, just a thought, you could always build with a local repo of Luminance instead of using the published crate, like here: https://stackoverflow.com/questions/33025887/how-to-use-a-local-unpublished-crate

Then you could modify your local Luminance to not have this behavior and add the versions to your shaders. Maybe this change would even be a welcome PR (you could make it scan the shader to see if it already has a version specified and only skip in that case).

**Comment by qingxiang-jia** [comment]
I think that totally makes sense. I am happy that I can contribute to the project. I will try to make a PR (no guarantee :smile: ).

BTW, I have also be learning WebGPU. Compared to raw WebGPU, Luminance is such a breeze.

**Comment by robert-chiniquy** [comment]
Yeah I really like it too. BTW, I said "maybe" above since I am not a project maintainer (don't want to misrepresent). A Luminance-style interface to WebGPU would be really cool, I feel like the current API may not cleanly map to WebGPU but I could be wrong.

**Comment by qingxiang-jia** [comment]
My only concern is its memory footprint is a bit large. A window with a triangle gives me 80+MB resident memory on ArchLinux (Xorg, Mesa driver). With the WebGPU (wgpu) one, I got only 50MB of resident memory.
